export const translatorArray = [
	{ name: 'Ukrainian', short: 'uk' },
	{ name: 'English', short: 'en' },
	{ name: 'Spanish', short: 'es' },
	{ name: 'French', short: 'fr' },
	{ name: 'German', short: 'de' },
	{ name: 'Italian', short: 'it' },
	{ name: 'Portuguese', short: 'pt' },
	{ name: 'Russian', short: 'ru' },
	{ name: 'Chinese', short: 'zh' },
	{ name: 'Japanese', short: 'ja' },
	{ name: 'Korean', short: 'ko' },
	{ name: 'Arabic', short: 'ar' },
	{ name: 'Dutch', short: 'nl' },
	{ name: 'Swedish', short: 'sv' },
	{ name: 'Norwegian', short: 'no' },
	{ name: 'Danish', short: 'da' },
	{ name: 'Finnish', short: 'fi' },
	{ name: 'Greek', short: 'el' },
	{ name: 'Turkish', short: 'tr' },
];
